/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/StatisticsCalculator.ts
var StatisticsCalculator_exports = {};
__export(StatisticsCalculator_exports, {
  StatisticsCalculator: () => StatisticsCalculator
});
var StatisticsCalculator;
var init_StatisticsCalculator = __esm({
  "src/StatisticsCalculator.ts"() {
    StatisticsCalculator = class {
      /**
       * Calculate statistics from session data
       * @param sessions Array of session data
       * @returns Statistics for today, this week, and this month
       */
      static calculate(sessions) {
        const now = /* @__PURE__ */ new Date();
        const startOfDay = this.getStartOfDay(now);
        const startOfWeek = this.getStartOfWeek(now);
        const startOfMonth = this.getStartOfMonth(now);
        const completedSessions = this.filterCompleted(sessions);
        const todaySessions = this.filterByDate(completedSessions, startOfDay, now);
        const weekSessions = this.filterByDate(completedSessions, startOfWeek, now);
        const monthSessions = this.filterByDate(completedSessions, startOfMonth, now);
        return {
          today: {
            completedSessions: todaySessions.length,
            totalMinutes: this.sumDuration(todaySessions)
          },
          thisWeek: {
            completedSessions: weekSessions.length,
            totalMinutes: this.sumDuration(weekSessions)
          },
          thisMonth: {
            completedSessions: monthSessions.length,
            totalMinutes: this.sumDuration(monthSessions)
          }
        };
      }
      /**
       * Filter sessions by date range
       * @param sessions Array of sessions
       * @param startDate Start date (inclusive)
       * @param endDate End date (inclusive)
       * @returns Filtered sessions
       */
      static filterByDate(sessions, startDate, endDate) {
        return sessions.filter((session) => {
          const [year, month, day] = session.date.split("-").map(Number);
          const sessionDate = new Date(year, month - 1, day);
          return sessionDate >= startDate && sessionDate <= endDate;
        });
      }
      /**
       * Filter only completed sessions
       * @param sessions Array of sessions
       * @returns Only sessions with status "completed"
       */
      static filterCompleted(sessions) {
        return sessions.filter((session) => session.status === "completed");
      }
      /**
       * Sum duration of sessions
       * @param sessions Array of sessions
       * @returns Total duration in minutes
       */
      static sumDuration(sessions) {
        return sessions.reduce((sum, session) => sum + session.duration, 0);
      }
      /**
       * Get start of day (00:00:00)
       * @param date Reference date (defaults to now)
       * @returns Date at start of day
       */
      static getStartOfDay(date = /* @__PURE__ */ new Date()) {
        const result = new Date(date);
        result.setHours(0, 0, 0, 0);
        return result;
      }
      /**
       * Get start of week (Monday 00:00:00)
       * @param date Reference date (defaults to now)
       * @returns Date at start of week
       */
      static getStartOfWeek(date = /* @__PURE__ */ new Date()) {
        const result = new Date(date);
        const day = result.getDay();
        const daysToSubtract = day === 0 ? 6 : day - 1;
        result.setDate(result.getDate() - daysToSubtract);
        result.setHours(0, 0, 0, 0);
        return result;
      }
      /**
       * Get start of month (1st day 00:00:00)
       * @param date Reference date (defaults to now)
       * @returns Date at start of month
       */
      static getStartOfMonth(date = /* @__PURE__ */ new Date()) {
        const result = new Date(date);
        result.setDate(1);
        result.setHours(0, 0, 0, 0);
        return result;
      }
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PomodoroPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  workDuration: 25,
  breakDuration: 5,
  soundEnabled: true,
  logFilePath: "pomodoro-log.md"
};

// src/validation.ts
var ValidationError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "ValidationError";
  }
};
function validateTaskName(taskName) {
  const trimmed = taskName.trim();
  if (trimmed.length === 0) {
    return { ok: false, error: new ValidationError("Task name cannot be empty") };
  }
  if (taskName.length > 100) {
    return { ok: false, error: new ValidationError("Task name cannot exceed 100 characters") };
  }
  return { ok: true, value: void 0 };
}
function truncateTaskName(taskName, maxLength = 100) {
  if (taskName.length <= maxLength) {
    return taskName;
  }
  return taskName.substring(0, maxLength);
}
function validateSettings(settings) {
  var _a, _b, _c, _d;
  const warnings = [];
  let workDuration = (_a = settings.workDuration) != null ? _a : 25;
  let breakDuration = (_b = settings.breakDuration) != null ? _b : 5;
  const soundEnabled = (_c = settings.soundEnabled) != null ? _c : true;
  let logFilePath = (_d = settings.logFilePath) != null ? _d : "pomodoro-log.md";
  if (typeof workDuration !== "number" || workDuration <= 0 || workDuration > 120) {
    warnings.push(`Invalid work duration (${workDuration}), using default (25 min)`);
    workDuration = 25;
  }
  if (typeof breakDuration !== "number" || breakDuration <= 0 || breakDuration > 60) {
    warnings.push(`Invalid break duration (${breakDuration}), using default (5 min)`);
    breakDuration = 5;
  }
  if (typeof logFilePath !== "string" || !logFilePath.endsWith(".md")) {
    warnings.push(`Invalid log file path (${logFilePath}), using default (pomodoro-log.md)`);
    logFilePath = "pomodoro-log.md";
  }
  return {
    workDuration,
    breakDuration,
    soundEnabled,
    logFilePath,
    warnings
  };
}

// src/TimerManager.ts
var TimerManager = class {
  constructor(settings) {
    this.intervalId = null;
    this.tickCallbacks = [];
    this.completeCallbacks = [];
    this.saveStateCallback = null;
    this.settings = settings;
    this.state = {
      isRunning: false,
      isPaused: false,
      remainingSeconds: 0,
      totalSeconds: 0,
      taskName: "",
      startTime: null,
      sessionType: "work"
    };
  }
  // Validate task name
  validateTaskName(taskName) {
    return validateTaskName(taskName);
  }
  // Start timer
  start(taskName, sessionType = "work") {
    const validation = this.validateTaskName(taskName);
    if (!validation.ok) {
      return validation;
    }
    if (this.state.isRunning) {
      return { ok: false, error: new ValidationError("Timer is already running") };
    }
    const duration = sessionType === "work" ? this.settings.workDuration : this.settings.breakDuration;
    this.state = {
      isRunning: true,
      isPaused: false,
      remainingSeconds: duration * 60,
      totalSeconds: duration * 60,
      taskName: taskName.trim(),
      startTime: /* @__PURE__ */ new Date(),
      sessionType
    };
    this.startInterval();
    if (this.saveStateCallback) {
      const serializable = this.getSerializableState();
      this.saveStateCallback(serializable);
    }
    return { ok: true, value: void 0 };
  }
  // Pause timer
  pause() {
    if (!this.state.isRunning) {
      console.warn("Cannot pause: timer is not running");
      return;
    }
    if (this.state.isPaused) {
      console.warn("Cannot pause: timer is already paused");
      return;
    }
    this.state.isPaused = true;
    this.stopInterval();
    if (this.saveStateCallback) {
      const serializable = this.getSerializableState();
      this.saveStateCallback(serializable);
    }
  }
  // Resume timer
  resume() {
    if (!this.state.isRunning) {
      console.warn("Cannot resume: timer is not running");
      return;
    }
    if (!this.state.isPaused) {
      console.warn("Cannot resume: timer is not paused");
      return;
    }
    const elapsed = this.state.totalSeconds - this.state.remainingSeconds;
    this.state.startTime = new Date(Date.now() - elapsed * 1e3);
    this.state.isPaused = false;
    this.startInterval();
  }
  // Stop timer — logs incomplete session via completeCallbacks
  stop() {
    if (!this.state.isRunning) {
      console.warn("Cannot stop: timer is not running");
      return null;
    }
    this.stopInterval();
    const elapsedSeconds = this.state.totalSeconds - this.state.remainingSeconds;
    const sessionData = {
      date: (/* @__PURE__ */ new Date()).toISOString().split("T")[0],
      startTime: this.state.startTime ? this.state.startTime.toTimeString().split(" ")[0] : "00:00:00",
      duration: Math.max(1, Math.floor(elapsedSeconds / 60)),
      taskName: this.state.taskName,
      status: "incomplete",
      sessionType: this.state.sessionType
    };
    this.state = {
      isRunning: false,
      isPaused: false,
      remainingSeconds: 0,
      totalSeconds: 0,
      taskName: "",
      startTime: null,
      sessionType: "work"
    };
    this.completeCallbacks.forEach((cb) => cb(sessionData));
    return sessionData;
  }
  // Force stop interval (for unload)
  stopInterval() {
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }
  // Start interval for a restored timer (after loadPersistedState)
  resumeInterval() {
    if (this.state.isRunning && !this.state.isPaused) {
      this.startInterval();
    }
  }
  // Get current state
  getState() {
    return { ...this.state };
  }
  // Get remaining time (calculated from Date)
  getRemainingTime() {
    if (!this.state.isRunning || this.state.isPaused || !this.state.startTime) {
      return this.state.remainingSeconds;
    }
    const elapsed = (Date.now() - this.state.startTime.getTime()) / 1e3;
    const remaining = Math.max(0, this.state.totalSeconds - elapsed);
    return Math.floor(remaining);
  }
  // Update settings (does not affect running timer)
  updateSettings(settings) {
    this.settings = settings;
  }
  // Register tick callback
  onTick(callback) {
    this.tickCallbacks.push(callback);
  }
  // Register complete callback
  onComplete(callback) {
    this.completeCallbacks.push(callback);
  }
  // Register save state callback (for auto-save)
  onSaveState(callback) {
    this.saveStateCallback = callback;
  }
  // Get serializable state (for persistence)
  getSerializableState() {
    return {
      ...this.state,
      startTime: this.state.startTime ? this.state.startTime.toISOString() : null
    };
  }
  // Load state from persistence
  loadPersistedState(serializedState) {
    this.state = {
      ...serializedState,
      startTime: serializedState.startTime ? new Date(serializedState.startTime) : null
    };
  }
  // Private: Handle completion
  startInterval() {
    let tickCount = 0;
    this.intervalId = window.setInterval(() => {
      if (this.state.isPaused) {
        return;
      }
      const remaining = this.getRemainingTime();
      this.state.remainingSeconds = remaining;
      this.tickCallbacks.forEach((cb) => cb(remaining, this.state.totalSeconds));
      tickCount++;
      if (tickCount >= 30 && this.saveStateCallback) {
        tickCount = 0;
        const serializable = this.getSerializableState();
        this.saveStateCallback(serializable);
      }
      if (remaining <= 0) {
        this.handleComplete();
      }
    }, 1e3);
  }
  // Private: Handle completion
  handleComplete() {
    this.stopInterval();
    const sessionData = {
      date: (/* @__PURE__ */ new Date()).toISOString().split("T")[0],
      startTime: this.state.startTime ? this.state.startTime.toTimeString().split(" ")[0] : "00:00:00",
      duration: Math.floor(this.state.totalSeconds / 60),
      taskName: this.state.taskName,
      status: "completed",
      sessionType: this.state.sessionType
    };
    this.state.isRunning = false;
    this.state.isPaused = false;
    this.completeCallbacks.forEach((cb) => cb(sessionData));
  }
};

// src/LogParser.ts
var LogParser = class {
  // Format header for Markdown table
  static formatHeader() {
    return [
      "| Date       | Start Time | Duration | Task Name        | Status     |",
      "| ---------- | ---------- | -------- | ---------------- | ---------- |"
    ].join("\n");
  }
  // Format a session as a Markdown table row
  static formatSession(session) {
    const { date, startTime, duration, taskName, status } = session;
    const escapedTaskName = taskName.replace(/\|/g, "\\|");
    return `| ${date} | ${startTime} | ${duration} | ${escapedTaskName} | ${status} |`;
  }
  // Parse entire log file content
  static parseLogFile(content) {
    const lines = content.split("\n");
    const sessions = [];
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line || line.startsWith("| Date") || line.startsWith("| ---")) {
        continue;
      }
      const session = this.parseRow(line);
      if (session) {
        sessions.push(session);
      } else {
        console.warn(`LogParser: Skipping invalid row at line ${i + 1}: ${line}`);
      }
    }
    return sessions;
  }
  // Parse a single row
  static parseRow(row) {
    if (!this.isValidRow(row)) {
      return null;
    }
    const columns = this.extractColumns(row);
    if (columns.length !== 5) {
      return null;
    }
    const [date, startTime, durationStr, taskName, status] = columns;
    if (!/^[+-]?\d{4,6}-\d{2}-\d{2}$/.test(date)) {
      return null;
    }
    if (!/^\d{2}:\d{2}:\d{2}$/.test(startTime)) {
      return null;
    }
    const duration = parseInt(durationStr, 10);
    if (isNaN(duration) || duration <= 0) {
      return null;
    }
    if (status !== "completed" && status !== "incomplete") {
      return null;
    }
    return {
      date,
      startTime,
      duration,
      taskName,
      status
    };
  }
  // Check if row is valid Markdown table row
  static isValidRow(row) {
    if (!row.startsWith("|") || !row.endsWith("|")) {
      return false;
    }
    const unescapedPipes = row.replace(/\\\|/g, "  ").match(/\|/g);
    const pipeCount = unescapedPipes ? unescapedPipes.length : 0;
    if (pipeCount < 6) {
      return false;
    }
    return true;
  }
  // Extract columns from a table row
  static extractColumns(row) {
    const content = row.slice(1, -1);
    const PIPE_PLACEHOLDER = "\0PIPE\0";
    const contentWithPlaceholders = content.replace(/\\\|/g, PIPE_PLACEHOLDER);
    const columns = contentWithPlaceholders.split("|").map((col) => col.trim());
    return columns.map((col) => col.replace(new RegExp(PIPE_PLACEHOLDER, "g"), "|"));
  }
};

// src/LogManager.ts
var LogError = class extends Error {
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = "LogError";
  }
};
var LogManager = class {
  constructor(vault, logFilePath) {
    this.vault = vault;
    this.logFilePath = logFilePath;
  }
  // Append a session to the log
  async appendSession(session) {
    try {
      const ensureResult = await this.ensureLogFileExists();
      if (!ensureResult.ok) {
        return ensureResult;
      }
      const existing = await this.vault.read(this.logFilePath);
      const newRow = LogParser.formatSession(session);
      const content = existing.trimEnd() + "\n" + newRow + "\n";
      await this.vault.write(this.logFilePath, content);
      return { ok: true, value: void 0 };
    } catch (error) {
      console.error("LogManager: Failed to append session", error);
      return {
        ok: false,
        error: new LogError("Failed to append session to log", error)
      };
    }
  }
  // Read all sessions from the log
  async readAllSessions() {
    try {
      const exists = await this.vault.exists(this.logFilePath);
      if (!exists) {
        return [];
      }
      const content = await this.vault.read(this.logFilePath);
      return LogParser.parseLogFile(content);
    } catch (error) {
      console.error("LogManager: Failed to read sessions", error);
      return [];
    }
  }
  // Read sessions within a date range
  async readSessionsInRange(startDate, endDate) {
    const allSessions = await this.readAllSessions();
    const startStr = startDate.toISOString().split("T")[0];
    const endStr = endDate.toISOString().split("T")[0];
    return allSessions.filter((session) => {
      return session.date >= startStr && session.date <= endStr;
    });
  }
  // Ensure log file exists with header
  async ensureLogFileExists() {
    try {
      const exists = await this.vault.exists(this.logFilePath);
      if (!exists) {
        const header = LogParser.formatHeader();
        await this.vault.write(this.logFilePath, header + "\n");
      }
      return { ok: true, value: void 0 };
    } catch (error) {
      console.error("LogManager: Failed to create log file", error);
      return {
        ok: false,
        error: new LogError("Failed to create log file", error)
      };
    }
  }
};

// src/NotificationManager.ts
var NotificationManager = class {
  constructor(settings) {
    this.settings = settings;
  }
  /**
   * Notify when timer starts
   * @param taskName Name of the task
   * @param duration Duration in minutes
   */
  notifyTimerStarted(taskName, duration) {
    const message = `\u23F1\uFE0F Timer started: "${taskName}" (${duration} min)`;
    this.showNotice(message);
  }
  /**
   * Notify when timer is paused
   * @param remainingTime Remaining time in seconds
   */
  notifyTimerPaused(remainingTime) {
    const minutes = Math.floor(remainingTime / 60);
    const seconds = remainingTime % 60;
    const timeStr = `${minutes}:${seconds.toString().padStart(2, "0")}`;
    const message = `\u23F8\uFE0F Timer paused (${timeStr} remaining)`;
    this.showNotice(message);
  }
  /**
   * Notify when timer completes
   * @param sessionType Type of session (work or break)
   */
  notifyTimerCompleted(sessionType) {
    const message = sessionType === "work" ? "\u2705 Work session completed! Time for a break." : "\u2705 Break completed! Ready to work.";
    this.showNotice(message);
    if (this.settings.soundEnabled) {
      this.playSound();
    }
  }
  notifyTimerStopped(sessionType) {
    const message = sessionType === "work" ? "\u23F9\uFE0F Work session stopped." : "\u23F9\uFE0F Break session stopped.";
    this.showNotice(message);
  }
  /**
   * Notify about incomplete session on startup
   * @param taskName Name of the task
   * @param remainingTime Remaining time in seconds
   */
  notifyIncompleteSession(taskName, remainingTime) {
    const minutes = Math.floor(remainingTime / 60);
    const seconds = remainingTime % 60;
    const timeStr = `${minutes}:${seconds.toString().padStart(2, "0")}`;
    const message = `\u26A0\uFE0F Incomplete session: "${taskName}" (${timeStr} remaining)`;
    this.showNotice(message, 1e4);
  }
  /**
   * Enable or disable sound notifications
   * @param enabled Whether sound is enabled
   */
  setSoundEnabled(enabled) {
    this.settings.soundEnabled = enabled;
  }
  /**
   * Update notification settings
   * @param settings New notification settings
   */
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * Play notification sound
   */
  playSound() {
    try {
      const audioContext = new (window.AudioContext || window.webkitAudioContext)();
      const oscillator = audioContext.createOscillator();
      const gainNode = audioContext.createGain();
      oscillator.connect(gainNode);
      gainNode.connect(audioContext.destination);
      oscillator.frequency.value = 800;
      oscillator.type = "sine";
      gainNode.gain.setValueAtTime(0.3, audioContext.currentTime);
      gainNode.gain.exponentialRampToValueAtTime(0.01, audioContext.currentTime + 0.5);
      oscillator.start(audioContext.currentTime);
      oscillator.stop(audioContext.currentTime + 0.5);
    } catch (error) {
      console.warn("NotificationManager: Failed to play sound", error);
    }
  }
  /**
   * Show a notice message
   * @param message Message to display
   * @param duration Duration in milliseconds (default 5000)
   */
  showNotice(message, duration = 5e3) {
    new Notice(message, duration);
  }
};

// src/SidebarView.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_POMODORO = "pomodoro-timer-view";
var SidebarView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.timerContainer = null;
    this.sessionBadge = null;
    this.timerDisplay = null;
    this.timerTask = null;
    this.progressRing = null;
    this.taskNameInput = null;
    this.startButton = null;
    this.pauseButton = null;
    this.resumeButton = null;
    this.stopButton = null;
    this.workDurationInput = null;
    this.breakDurationInput = null;
    this.soundEnabledCheckbox = null;
    this.statisticsContainer = null;
    this.refreshStatsButton = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_POMODORO;
  }
  getDisplayText() {
    return "Pomodoro";
  }
  getIcon() {
    return "timer";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("pomodoro-sidebar");
    this.renderTimerSection(container);
    this.renderTaskSection(container);
    this.renderControlsSection(container);
    this.renderQuickActions(container);
    this.renderSettingsSection(container);
    this.renderStatisticsSection(container);
    await this.refreshStatistics();
    this.syncWithTimer();
  }
  async onClose() {
  }
  syncWithTimer() {
    if (this.plugin.timerManager) {
      const state = this.plugin.timerManager.getState();
      if (state.isRunning) {
        this.updateTimerDisplay(state.remainingSeconds, state.totalSeconds);
        this.updateProgress(state.remainingSeconds, state.totalSeconds);
        this.updateControlButtons(state);
        this.updateSessionUI(state.sessionType, state.taskName);
      }
    }
  }
  renderTimerSection(container) {
    this.timerContainer = container.createDiv({ cls: "pmd-timer" });
    this.sessionBadge = this.timerContainer.createDiv({ cls: "pmd-badge pmd-badge--work" });
    this.sessionBadge.setText("focus");
    const progressContainer = this.timerContainer.createDiv({ cls: "pmd-ring-wrap" });
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("class", "pmd-ring");
    svg.setAttribute("width", "200");
    svg.setAttribute("height", "200");
    svg.setAttribute("viewBox", "0 0 200 200");
    progressContainer.appendChild(svg);
    const bgCircle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    bgCircle.setAttribute("class", "pmd-ring__bg");
    bgCircle.setAttribute("cx", "100");
    bgCircle.setAttribute("cy", "100");
    bgCircle.setAttribute("r", "90");
    svg.appendChild(bgCircle);
    const circumference = 2 * Math.PI * 90;
    this.progressRing = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    this.progressRing.setAttribute("class", "pmd-ring__fill");
    this.progressRing.setAttribute("cx", "100");
    this.progressRing.setAttribute("cy", "100");
    this.progressRing.setAttribute("r", "90");
    this.progressRing.setAttribute("stroke-dasharray", circumference.toString());
    this.progressRing.setAttribute("stroke-dashoffset", "0");
    svg.appendChild(this.progressRing);
    const overlay = progressContainer.createDiv({ cls: "pmd-ring__overlay" });
    this.timerDisplay = overlay.createDiv({ cls: "pmd-time" });
    this.timerDisplay.setText("25:00");
    this.timerTask = this.timerContainer.createDiv({ cls: "pmd-task-label" });
    this.timerTask.setText("ready to focus");
  }
  renderTaskSection(container) {
    const section = container.createDiv({ cls: "pmd-section" });
    section.createEl("label", { text: "What are you working on?", cls: "pmd-label" });
    this.taskNameInput = section.createEl("input", {
      type: "text",
      placeholder: "Enter task name...",
      cls: "pmd-input"
    });
    this.taskNameInput.addEventListener("input", () => {
      if (this.taskNameInput) {
        if (this.taskNameInput.value.length > 100) {
          this.taskNameInput.value = truncateTaskName(this.taskNameInput.value);
        }
        const validation = validateTaskName(this.taskNameInput.value);
        if (validation.ok) {
          this.taskNameInput.removeClass("pmd-input--invalid");
        } else {
          this.taskNameInput.addClass("pmd-input--invalid");
        }
      }
    });
  }
  renderControlsSection(container) {
    var _a;
    const section = container.createDiv({ cls: "pmd-controls" });
    this.startButton = section.createEl("button", {
      text: "start",
      cls: "pmd-btn pmd-btn--primary"
    });
    this.pauseButton = section.createEl("button", {
      text: "pause",
      cls: "pmd-btn pmd-btn--secondary"
    });
    this.resumeButton = section.createEl("button", {
      text: "resume",
      cls: "pmd-btn pmd-btn--primary"
    });
    this.stopButton = section.createEl("button", {
      text: "stop",
      cls: "pmd-btn pmd-btn--ghost"
    });
    this.startButton.addEventListener("click", () => this.handleStart());
    this.pauseButton.addEventListener("click", () => this.handlePause());
    this.resumeButton.addEventListener("click", () => this.handleResume());
    this.stopButton.addEventListener("click", () => this.handleStop());
    this.updateControlButtons(((_a = this.plugin.timerManager) == null ? void 0 : _a.getState()) || this.getDefaultState());
  }
  renderQuickActions(container) {
    const section = container.createDiv({ cls: "pmd-section" });
    const header = section.createDiv({ cls: "pmd-section-header" });
    header.createEl("span", { text: "quick start", cls: "pmd-label" });
    const pillsContainer = section.createDiv({ cls: "pmd-pills" });
    const pomodoroBtn = pillsContainer.createEl("button", {
      text: "25m",
      cls: "pmd-pill pmd-pill--active",
      attr: { "data-duration": "25" }
    });
    const shortBtn = pillsContainer.createEl("button", {
      text: "15m",
      cls: "pmd-pill",
      attr: { "data-duration": "15" }
    });
    const longBtn = pillsContainer.createEl("button", {
      text: "45m",
      cls: "pmd-pill",
      attr: { "data-duration": "45" }
    });
    [pomodoroBtn, shortBtn, longBtn].forEach((btn) => {
      btn.addEventListener("click", () => {
        const duration = parseInt(btn.getAttribute("data-duration") || "25", 10);
        this.plugin.settings.workDuration = duration;
        if (this.workDurationInput) {
          this.workDurationInput.value = duration.toString();
        }
        this.plugin.saveSettings();
        document.querySelectorAll(".pmd-pill").forEach((b) => b.classList.remove("pmd-pill--active"));
        btn.classList.add("pmd-pill--active");
      });
    });
  }
  renderSettingsSection(container) {
    const section = container.createDiv({ cls: "pmd-section" });
    const header = section.createDiv({ cls: "pmd-section-header" });
    header.createEl("span", { text: "settings", cls: "pmd-label" });
    const grid = section.createDiv({ cls: "pmd-settings-grid" });
    const workGroup = grid.createDiv({ cls: "pmd-field" });
    workGroup.createEl("label", { text: "work (min)", cls: "pmd-field__label" });
    this.workDurationInput = workGroup.createEl("input", {
      type: "number",
      value: this.plugin.settings.workDuration.toString(),
      cls: "pmd-field__input",
      attr: { min: "1", max: "120" }
    });
    this.workDurationInput.addEventListener("change", () => this.handleSettingsChange());
    const breakGroup = grid.createDiv({ cls: "pmd-field" });
    breakGroup.createEl("label", { text: "break (min)", cls: "pmd-field__label" });
    this.breakDurationInput = breakGroup.createEl("input", {
      type: "number",
      value: this.plugin.settings.breakDuration.toString(),
      cls: "pmd-field__input",
      attr: { min: "1", max: "60" }
    });
    this.breakDurationInput.addEventListener("change", () => this.handleSettingsChange());
    const soundGroup = section.createDiv({ cls: "pmd-toggle-row" });
    this.soundEnabledCheckbox = soundGroup.createEl("input", {
      type: "checkbox",
      cls: "pmd-toggle",
      attr: { id: "pmd-sound-toggle" }
    });
    this.soundEnabledCheckbox.checked = this.plugin.settings.soundEnabled;
    soundGroup.createEl("label", {
      text: "sound notifications",
      cls: "pmd-toggle-label",
      attr: { for: "pmd-sound-toggle" }
    });
    this.soundEnabledCheckbox.addEventListener("change", () => this.handleSettingsChange());
  }
  renderStatisticsSection(container) {
    const section = container.createDiv({ cls: "pmd-section pmd-section--stats" });
    const header = section.createDiv({ cls: "pmd-section-header" });
    header.createEl("span", { text: "statistics", cls: "pmd-label" });
    this.refreshStatsButton = header.createEl("button", {
      cls: "pmd-refresh",
      attr: { title: "Refresh statistics" }
    });
    (0, import_obsidian.setIcon)(this.refreshStatsButton, "refresh-cw");
    this.refreshStatsButton.addEventListener("click", () => this.refreshStatistics());
    this.statisticsContainer = section.createDiv({ cls: "pmd-stats" });
  }
  getDefaultState() {
    return {
      isRunning: false,
      isPaused: false,
      remainingSeconds: this.plugin.settings.workDuration * 60,
      totalSeconds: this.plugin.settings.workDuration * 60,
      taskName: "",
      startTime: null,
      sessionType: "work"
    };
  }
  updateTimerDisplay(remainingSeconds, totalSeconds = 0) {
    if (!this.timerDisplay)
      return;
    const minutes = Math.floor(remainingSeconds / 60);
    const seconds = remainingSeconds % 60;
    const timeString = `${minutes.toString().padStart(2, "0")}:${seconds.toString().padStart(2, "0")}`;
    this.timerDisplay.setText(timeString);
  }
  updateProgress(remaining, total) {
    if (!this.progressRing)
      return;
    const circumference = 2 * Math.PI * 90;
    const progress = total > 0 ? remaining / total : 1;
    const offset = circumference * (1 - progress);
    this.progressRing.style.strokeDashoffset = offset.toString();
  }
  updateSessionUI(sessionType, taskName) {
    if (!this.sessionBadge || !this.timerContainer || !this.timerTask)
      return;
    if (sessionType === "break") {
      this.timerContainer.classList.add("pmd-timer--break");
      this.sessionBadge.classList.remove("pmd-badge--work");
      this.sessionBadge.classList.add("pmd-badge--break");
      this.sessionBadge.setText("break");
      this.timerTask.setText("take a break");
    } else {
      this.timerContainer.classList.remove("pmd-timer--break");
      this.sessionBadge.classList.remove("pmd-badge--break");
      this.sessionBadge.classList.add("pmd-badge--work");
      this.sessionBadge.setText("focus");
      this.timerTask.setText(taskName || "ready to focus");
    }
  }
  updateControlButtons(state) {
    var _a, _b, _c;
    if (!this.startButton || !this.pauseButton || !this.resumeButton || !this.stopButton) {
      return;
    }
    this.setSettingsEnabled(!state.isRunning);
    if (state.isRunning && !state.isPaused) {
      (_a = this.timerContainer) == null ? void 0 : _a.classList.add("pmd-timer--running");
      this.startButton.style.display = "none";
      this.pauseButton.style.display = "flex";
      this.resumeButton.style.display = "none";
      this.stopButton.style.display = "flex";
      this.pauseButton.disabled = false;
      this.stopButton.disabled = false;
    } else if (state.isRunning && state.isPaused) {
      (_b = this.timerContainer) == null ? void 0 : _b.classList.remove("pmd-timer--running");
      this.startButton.style.display = "none";
      this.pauseButton.style.display = "flex";
      this.resumeButton.style.display = "flex";
      this.stopButton.style.display = "flex";
      this.pauseButton.disabled = true;
      this.resumeButton.disabled = false;
      this.stopButton.disabled = false;
    } else {
      (_c = this.timerContainer) == null ? void 0 : _c.classList.remove("pmd-timer--running");
      this.startButton.style.display = "flex";
      this.pauseButton.style.display = "none";
      this.resumeButton.style.display = "none";
      this.stopButton.style.display = "none";
      this.startButton.disabled = false;
    }
  }
  updateStatistics(stats) {
    if (!this.statisticsContainer)
      return;
    this.statisticsContainer.empty();
    const periods = [
      { key: "today", label: "today" },
      { key: "thisWeek", label: "week" },
      { key: "thisMonth", label: "month" }
    ];
    periods.forEach((period) => {
      const statData = stats[period.key];
      const card = this.statisticsContainer.createDiv({ cls: "pmd-stat" });
      card.createDiv({ cls: "pmd-stat__period", text: period.label });
      const valueDiv = card.createDiv({ cls: "pmd-stat__value" });
      valueDiv.setText(statData.completedSessions.toString());
      card.createDiv({ cls: "pmd-stat__unit", text: `${statData.totalMinutes}m` });
    });
  }
  setSettingsEnabled(enabled) {
    this.workDurationInput && (this.workDurationInput.disabled = !enabled);
    this.breakDurationInput && (this.breakDurationInput.disabled = !enabled);
  }
  async refreshStatistics() {
    if (!this.refreshStatsButton)
      return;
    this.refreshStatsButton.classList.add("pmd-refresh--spinning");
    try {
      if (!this.plugin.logManager)
        return;
      const sessions = await this.plugin.logManager.readAllSessions();
      const stats = await Promise.resolve().then(() => (init_StatisticsCalculator(), StatisticsCalculator_exports)).then(
        (m) => m.StatisticsCalculator.calculate(sessions)
      );
      this.updateStatistics(stats);
    } catch (error) {
      console.error("Failed to refresh statistics", error);
      this.updateStatistics({
        today: { completedSessions: 0, totalMinutes: 0 },
        thisWeek: { completedSessions: 0, totalMinutes: 0 },
        thisMonth: { completedSessions: 0, totalMinutes: 0 }
      });
    } finally {
      setTimeout(() => {
        var _a;
        return (_a = this.refreshStatsButton) == null ? void 0 : _a.classList.remove("pmd-refresh--spinning");
      }, 500);
    }
  }
  handleStart() {
    if (!this.taskNameInput || !this.plugin.timerManager)
      return;
    const taskName = this.taskNameInput.value;
    const validation = validateTaskName(taskName);
    if (!validation.ok) {
      new import_obsidian.Notice(`\u26A0\uFE0F ${validation.error.message}`, 3e3);
      this.taskNameInput.addClass("pmd-input--invalid");
      return;
    }
    const result = this.plugin.timerManager.start(taskName, "work");
    if (!result.ok) {
      new import_obsidian.Notice(`\u26A0\uFE0F ${result.error.message}`, 3e3);
      return;
    }
    if (this.plugin.notificationManager) {
      this.plugin.notificationManager.notifyTimerStarted(taskName, this.plugin.settings.workDuration);
    }
    const state = this.plugin.timerManager.getState();
    this.updateControlButtons(state);
    this.updateTimerDisplay(state.remainingSeconds, state.totalSeconds);
    this.updateProgress(state.remainingSeconds, state.totalSeconds);
    this.updateSessionUI(state.sessionType, taskName);
  }
  handlePause() {
    var _a;
    if (!this.plugin.timerManager)
      return;
    this.plugin.timerManager.pause();
    if (this.plugin.notificationManager) {
      this.plugin.notificationManager.notifyTimerPaused(this.plugin.timerManager.getRemainingTime());
    }
    const state = this.plugin.timerManager.getState();
    this.updateControlButtons(state);
    (_a = this.timerContainer) == null ? void 0 : _a.classList.remove("pmd-timer--running");
  }
  handleResume() {
    var _a;
    if (!this.plugin.timerManager)
      return;
    this.plugin.timerManager.resume();
    const state = this.plugin.timerManager.getState();
    this.updateControlButtons(state);
    (_a = this.timerContainer) == null ? void 0 : _a.classList.add("pmd-timer--running");
  }
  handleStop() {
    var _a;
    if (!this.plugin.timerManager)
      return;
    this.plugin.timerManager.stop();
    if (this.taskNameInput) {
      this.taskNameInput.value = "";
      this.taskNameInput.removeClass("pmd-input--invalid");
    }
    const state = this.plugin.timerManager.getState();
    const defaultState = this.getDefaultState();
    this.updateControlButtons(state);
    this.updateTimerDisplay(defaultState.remainingSeconds);
    this.updateProgress(defaultState.remainingSeconds, defaultState.totalSeconds);
    this.updateSessionUI("work", "");
    (_a = this.timerContainer) == null ? void 0 : _a.classList.remove("pmd-timer--running", "pmd-timer--break");
  }
  async handleSettingsChange() {
    var _a;
    if (!this.workDurationInput || !this.breakDurationInput || !this.soundEnabledCheckbox)
      return;
    try {
      const workDuration = parseInt(this.workDurationInput.value, 10);
      const breakDuration = parseInt(this.breakDurationInput.value, 10);
      if (isNaN(workDuration) || workDuration <= 0 || workDuration > 120) {
        new import_obsidian.Notice("\u26A0\uFE0F Work: 1-120 min", 3e3);
        this.workDurationInput.value = this.plugin.settings.workDuration.toString();
        return;
      }
      if (isNaN(breakDuration) || breakDuration <= 0 || breakDuration > 60) {
        new import_obsidian.Notice("\u26A0\uFE0F Break: 1-60 min", 3e3);
        this.breakDurationInput.value = this.plugin.settings.breakDuration.toString();
        return;
      }
      this.plugin.settings.workDuration = workDuration;
      this.plugin.settings.breakDuration = breakDuration;
      this.plugin.settings.soundEnabled = this.soundEnabledCheckbox.checked;
      await this.plugin.saveSettings();
      if (!((_a = this.plugin.timerManager) == null ? void 0 : _a.getState().isRunning)) {
        const defaultState = this.getDefaultState();
        this.updateTimerDisplay(defaultState.remainingSeconds);
        this.updateProgress(defaultState.remainingSeconds, defaultState.totalSeconds);
      }
    } catch (error) {
      console.error("Failed to save settings", error);
    }
  }
};

// src/main.ts
var ObsidianVaultAdapter = class {
  constructor(vault) {
    this.vault = vault;
  }
  async exists(path) {
    return await this.vault.adapter.exists(path);
  }
  async read(path) {
    return await this.vault.adapter.read(path);
  }
  async write(path, data) {
    await this.vault.adapter.write(path, data);
  }
};
var PomodoroPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.timerManager = null;
    this.logManager = null;
    this.notificationManager = null;
    this.sidebarView = null;
    this._pendingSession = null;
  }
  async onload() {
    console.log("Loading Enhanced Pomodoro Timer plugin");
    await this.loadSettings();
    this.timerManager = new TimerManager(this.settings);
    this.logManager = new LogManager(
      new ObsidianVaultAdapter(this.app.vault),
      this.settings.logFilePath
    );
    this.notificationManager = new NotificationManager({
      soundEnabled: this.settings.soundEnabled
    });
    this.timerManager.onSaveState(async (serializedState) => {
      await this.saveTimerState(serializedState);
    });
    this.timerManager.onTick((remainingSeconds, totalSeconds) => {
      this.onTimerTick(remainingSeconds, totalSeconds);
    });
    this.timerManager.onComplete((sessionData) => {
      this.onTimerComplete(sessionData);
    });
    this.registerView(
      VIEW_TYPE_POMODORO,
      (leaf) => {
        this.sidebarView = new SidebarView(leaf, this);
        return this.sidebarView;
      }
    );
    await this.checkIncompleteSession();
    this.addCommand({
      id: "open-pomodoro-sidebar",
      name: "Open Pomodoro Timer",
      callback: () => {
        this.activateSidebarView();
      }
    });
    if (this.app.workspace) {
      this.activateSidebarView();
    }
  }
  async onunload() {
    console.log("Unloading Enhanced Pomodoro Timer plugin");
    if (this.timerManager) {
      const state = this.timerManager.getState();
      if (state.isRunning) {
        this.timerManager.stopInterval();
        try {
          await this.saveTimerState(state);
          console.log("Timer state saved on unload:", state.taskName);
        } catch (e) {
          console.error("Failed to save timer state on unload:", e);
        }
      }
      if (this._pendingSession) {
        try {
          const data = await this.loadData();
          data.pendingSession = this._pendingSession;
          await this.saveData(data);
        } catch (e) {
          console.error("Failed to save pending session on unload:", e);
        }
      }
    }
    this.timerManager = null;
    this.logManager = null;
    this.notificationManager = null;
    this.sidebarView = null;
  }
  // Load settings from disk
  async loadSettings() {
    try {
      const data = await this.loadData();
      const rawSettings = (data == null ? void 0 : data.settings) || {};
      const validated = validateSettings(rawSettings);
      if (validated.warnings.length > 0) {
        console.warn("Settings validation warnings:", validated.warnings);
        new import_obsidian2.Notice(`\u26A0\uFE0F Settings issues detected:
${validated.warnings.join("\n")}`, 8e3);
      }
      this.settings = {
        workDuration: validated.workDuration,
        breakDuration: validated.breakDuration,
        soundEnabled: validated.soundEnabled,
        logFilePath: validated.logFilePath
      };
    } catch (error) {
      console.error("Failed to load settings, using defaults", error);
      this.settings = { ...DEFAULT_SETTINGS };
      new import_obsidian2.Notice("\u26A0\uFE0F Failed to load settings, using defaults", 5e3);
    }
  }
  // Save settings to disk
  async saveSettings() {
    try {
      const validated = validateSettings(this.settings);
      if (validated.warnings.length > 0) {
        console.warn("Settings validation warnings:", validated.warnings);
        new import_obsidian2.Notice(`\u26A0\uFE0F Settings corrected:
${validated.warnings.join("\n")}`, 8e3);
      }
      this.settings = {
        workDuration: validated.workDuration,
        breakDuration: validated.breakDuration,
        soundEnabled: validated.soundEnabled,
        logFilePath: validated.logFilePath
      };
      await this.saveData({ settings: this.settings });
      if (this.timerManager) {
        this.timerManager.updateSettings(this.settings);
      }
      if (this.notificationManager) {
        this.notificationManager.updateSettings({
          soundEnabled: this.settings.soundEnabled
        });
      }
    } catch (error) {
      console.error("Failed to save settings", error);
      new import_obsidian2.Notice("\u26A0\uFE0F Failed to save settings. Changes may not persist.", 5e3);
    }
  }
  // Event handler: Timer tick
  onTimerTick(remainingSeconds, totalSeconds) {
    if (this.sidebarView) {
      this.sidebarView.updateTimerDisplay(remainingSeconds, totalSeconds);
    }
  }
  // Event handler: Timer complete
  async onTimerComplete(sessionData) {
    var _a, _b, _c, _d;
    this._pendingSession = sessionData;
    try {
      if (this.logManager) {
        const result = await this.logManager.appendSession(sessionData);
        if (!result.ok) {
          console.error("Failed to log session:", result.error);
          new import_obsidian2.Notice("\u26A0\uFE0F Failed to save session to log. Session data may be lost.", 8e3);
        }
      }
      const sessionType = (_a = sessionData.sessionType) != null ? _a : "work";
      if (sessionData.status === "completed") {
        (_b = this.notificationManager) == null ? void 0 : _b.notifyTimerCompleted(sessionType);
      } else {
        (_c = this.notificationManager) == null ? void 0 : _c.notifyTimerStopped(sessionType);
      }
      if (this.sidebarView) {
        try {
          const sessions = await ((_d = this.logManager) == null ? void 0 : _d.readAllSessions()) || [];
          const { StatisticsCalculator: StatisticsCalculator2 } = await Promise.resolve().then(() => (init_StatisticsCalculator(), StatisticsCalculator_exports));
          const stats = StatisticsCalculator2.calculate(sessions);
          this.sidebarView.updateStatistics(stats);
        } catch (statsError) {
          console.error("Failed to refresh statistics", statsError);
          new import_obsidian2.Notice("\u26A0\uFE0F Failed to refresh statistics. Check console for details.", 5e3);
        }
        if (this.timerManager) {
          this.sidebarView.updateControlButtons(this.timerManager.getState());
        }
      }
      await this.clearTimerState();
    } catch (error) {
      console.error("Failed to handle timer completion", error);
      new import_obsidian2.Notice("\u26A0\uFE0F Failed to complete timer session. Check console for details.", 8e3);
    } finally {
      this._pendingSession = null;
    }
  }
  // Activate sidebar view
  async activateSidebarView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_POMODORO);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: VIEW_TYPE_POMODORO,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  // Check for incomplete session on startup
  async checkIncompleteSession() {
    try {
      const data = await this.loadData();
      let needsSave = false;
      if (data == null ? void 0 : data.pendingSession) {
        if (this.logManager) {
          try {
            await this.logManager.appendSession(data.pendingSession);
          } catch (e) {
            console.error("Failed to log pending session:", e);
          }
        }
        delete data.pendingSession;
        needsSave = true;
      }
      const persistedState = (data == null ? void 0 : data.timerState) || null;
      if (persistedState && persistedState.state.isRunning) {
        const hoursSinceClose = (Date.now() - persistedState.timestamp) / (1e3 * 60 * 60);
        if (hoursSinceClose > 24) {
          const pState = persistedState.state;
          const elapsedSeconds = pState.totalSeconds - pState.remainingSeconds;
          const incompleteSession = {
            date: new Date(persistedState.timestamp).toISOString().split("T")[0],
            startTime: pState.startTime ? new Date(pState.startTime).toTimeString().split(" ")[0] : "00:00:00",
            duration: Math.max(1, Math.floor(elapsedSeconds / 60)),
            taskName: pState.taskName,
            status: "incomplete",
            sessionType: pState.sessionType
          };
          if (this.logManager) {
            await this.logManager.appendSession(incompleteSession);
          }
          delete data.timerState;
          needsSave = true;
        } else if (this.timerManager) {
          this.timerManager.loadPersistedState(persistedState.state);
          this.timerManager.resumeInterval();
          const remaining = this.timerManager.getRemainingTime();
          const timerState = this.timerManager.getState();
          if (this.sidebarView) {
            this.sidebarView.updateTimerDisplay(remaining, timerState.totalSeconds);
            this.sidebarView.updateProgress(remaining, timerState.totalSeconds);
            this.sidebarView.updateControlButtons(timerState);
            this.sidebarView.updateSessionUI(timerState.sessionType, timerState.taskName);
          }
          new import_obsidian2.Notice(`\u{1F504} Timer restored: ${timerState.taskName}`, 5e3);
          console.log("Timer restored:", timerState.taskName);
        }
      }
      if (needsSave) {
        await this.saveData(data);
      }
    } catch (error) {
      console.error("Failed to check incomplete session", error);
    }
  }
  // Save timer state for recovery
  async saveTimerState(state) {
    try {
      const data = await this.loadData();
      const persistedState = {
        state: {
          ...state,
          // Convert Date to ISO string for serialization
          startTime: state.startTime ? state.startTime.toISOString() : null
        },
        timestamp: Date.now()
      };
      await this.saveData({
        ...data,
        timerState: persistedState
      });
    } catch (error) {
      console.error("Failed to save timer state", error);
      new import_obsidian2.Notice("\u26A0\uFE0F Failed to save timer state. Session may not be recoverable if app closes.", 5e3);
    }
  }
  // Clear persisted timer state
  async clearTimerState() {
    try {
      const data = await this.loadData();
      if (data == null ? void 0 : data.timerState) {
        delete data.timerState;
        await this.saveData(data);
      }
    } catch (error) {
      console.error("Failed to clear timer state", error);
    }
  }
};
